version: '3.3'
services:
    db:
      image: mysql:5.7
      volumes:
       - ./data-init:/docker-entrypoint-initdb.d  
      environment:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: db_test
          MYSQL_USER: username
          MYSQL_PASSWORD: password
    api1:
      build: ./out_api/api1
      image: erwankerbrat/api1
      depends_on:
        - db
      ports:
        - "1234:5000" 
      environment:
        DATABASE_URL: "mysql://root:rootpassword@db:3306/db_test"
